import { ExpenseCategory } from "@prisma/client";

export interface CreateExpenseData {
    tripId: string;
    userId: string;
    description: string;
    amount: number;
    category: ExpenseCategory;
    date: Date;
    isAutogenerated?: boolean; // Optional flag for autogenerated expenses
}

export interface UpdateExpenseData {
    description?: string;
    amount?: number;
    category?: ExpenseCategory;
    date?: Date;
}

export interface BudgetAnalysis {
    totalSpent: number;
    totalBudget: number;
    remainingBudget: number;
    spentPercentage: number;
    categoryBreakdown: Record<string, { amount: number; percentage: number }>;
    dailyAverage: number;
    projectedTotal: number;
    recommendations: string[];
}

export interface BudgetOptimizationRequest {
    tripId: string;
    startDate: Date;
    endDate: Date;
    destinationName: string;
    currentBudget: number;
    currentExpenses: any[];
    preferences?: string[];
}